                                              Assignment-4 : Numpy 

In [1]:
import numpy as np

In [4]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr = np.array([0, 1, 2, 3, 4, 5])
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
arr.dtype

dtype('int64')

In [8]:
# 2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [9]:
arr.dtype

dtype('float64')

In [11]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

In [12]:
arr

array([1.+2.j, 3.+4.j, 5.+6.j])

In [13]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([1, 2, 3, 4, 5])

In [15]:
arr.dtype

dtype('int64')

In [16]:
arr_f32 = arr.astype(np.float32)

In [17]:
arr_f32

array([1., 2., 3., 4., 5.], dtype=float32)

In [19]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.123456789, 2.987654321, 3.141592653], dtype=np.float64)

In [21]:
arr.dtype

dtype('float64')

In [22]:
arr_f32 = arr.astype(np.float32)

In [23]:
arr_f32

array([1.1234568, 2.9876542, 3.1415927], dtype=float32)

In [24]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

def array_attributes(arr):
    if isinstance(arr, np.ndarray):
        return arr.shape, arr.size, arr.dtype
    else:
        raise ValueError("Input must be a Numpy array")
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)

In [25]:
shape

(2, 3)

In [26]:
size

6

In [27]:
dtype

dtype('int64')

In [28]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    return arr.ndim

In [29]:
arr1 = np.array([1, 2, 3])
array_dimension(arr1)

1

In [30]:
arr2 = np.array([[1, 2], [3, 4]])
array_dimension(arr2)

2

In [31]:
arr3 = np.array([[[1], [2]], [[3], [4]]])
array_dimension(arr3)

3

In [32]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.size * item_size
    return item_size, total_size
arr1 = np.array([1, 2, 3, 4])
item_size, total_size = item_size_info(arr1)

In [33]:
item_size

8

In [34]:
total_size

32

In [35]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2], [3, 4]])
arr3 = np.array([[[1], [2]], [[3], [4]]])

In [36]:
array_strides(arr1)

(8,)

In [37]:
array_strides(arr2)

(16, 8)

In [38]:
array_strides(arr3)

(16, 8, 8)

In [41]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
arr1 = np.array([[[1], [2]], [[3], [4]]])
shape, strides = shape_stride_relationship(arr1)

In [42]:
shape

(2, 2, 1)

In [43]:
strides

(16, 8, 8)

In [49]:
# 11. Create a function "create_zeros_array that takes an integer 'n' as input and returns a NumPy array of zeros with 'n' elements.
def create_zeros_array(n):
    return np.zeros(n)
    
arr = create_zeros_array(5)
arr

array([0., 0., 0., 0., 0.])

In [50]:
# 12. Write a function `create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size `rows x cols.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
    
mat = create_ones_matrix(3, 4)
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
    
arr = generate_range_array(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [52]:
# 14. Design a function `generate_linear_space that takes two floats start`, `stop`, and an integer `num`as arguments and generates a NumPy array with num equally spaced values between 'start' and `stop` (inclusive).
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

arr = generate_linear_space(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [53]:
# 15. Create a function `create_identity_matrix that takes an integer `n` as input and generates a square identity matrix of size `n x n' using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)
mat_3x3 = create_identity_matrix(3)
mat_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def  numpy_array(py_list):
    return np.array(py_list)
    
py_list1 = [1, 2, 3, 4, 5]
l1 = numpy_array(py_list1)
py_list2 = [[1, 2], [3, 4], [5, 6]]
l2 = numpy_array(py_list2)

In [56]:
l1

array([1, 2, 3, 4, 5])

In [57]:
l2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
# 17. Create a NumPy array and demonstrate the use of 'numpy.view to create a new array object with the same data.
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()
view_arr

array([1, 2, 3, 4, 5])

In [60]:
view_arr[0] = 100

In [61]:
view_arr

array([100,   2,   3,   4,   5])

In [63]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result1 = concatenate_arrays(arr1, arr2)
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])
result2 = concatenate_arrays(arr1_2d, arr2_2d, axis=0)

In [64]:
result1

array([1, 2, 3, 4, 5, 6])

In [65]:
result2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using 'numpy. concatenate.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10]])

result = np.concatenate((arr1, arr2), axis=1)

In [68]:
arr1

array([[1, 2],
       [3, 4]])

In [69]:
arr2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [70]:
result

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

In [72]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def stack_arrays_vertically(arrays_list):
    return np.vstack(arrays_list)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

arr = [arr1, arr2, arr3]
result = stack_arrays_vertically(arr)

In [73]:
result

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [74]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create_integer_array(start, stop, step):
    return np.arange(start, stop + 1, step)
arr = create_integer_array(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [75]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def generate_equally_spaced(start, stop, num_values):
    return np.linspace(start, stop, num_values)
arr = generate_equally_spaced(0, 1, 10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [76]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def generate_logarithmically_spaced_values(start, stop, num_values):
    return np.logspace(np.log10(start), np.log10(stop), num_values)
arr = generate_logarithmically_spaced_values(1, 1000, 5)
arr

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [1]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import numpy as np
import pandas as pd

np_array = np.random.randint(1, 100, size=(5, 3))
df = pd.DataFrame(np_array, columns=['Column1', 'Column2', 'Column3'])
print(df)

   Column1  Column2  Column3
0       27       20       55
1       23       66       45
2       45       86        3
3       92       35       72
4       68       57       80


In [5]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, -5]
}
df = pd.DataFrame(data)

df = replace_negatives_with_zero(df, 'A')

print(df)

   A  B
0  1 -1
1  0  2
2  3 -3
3  0  4
4  5 -5


In [80]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr[2]

np.int64(30)

In [81]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2]
element

np.int64(6)

In [85]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
val = arr > 5
greater = arr[val]
greater

array([ 8, 10,  7])

In [86]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. I
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:5]

array([3, 4, 5])

In [107]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]] from the given array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
sub_array

array([[2, 3],
       [5, 6]])

In [108]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(arr_2d, indices):
    rows, cols = indices[:, 0], indices[:, 1]
    return arr_2d[rows, cols]
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]])
extracted_elements = extract_elements(arr_2d, indices)
extracted_elements

array([2, 6, 7])

In [109]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given ID array using boolean indexing.
def filter_elements_greater_than_threshold(arr, threshold):
    mask = arr > threshold
    filtered_elements = arr[mask]
    return filtered_elements

arr = np.array([10, 20, 5, 40, 30, 15])
threshold = 15

filtered_arr = filter_elements_greater_than_threshold(arr, threshold)
print(filtered_arr)

[20 40 30]


In [110]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices):
    return arr_3d[row_indices, col_indices, depth_indices]

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]]])
row_indices = np.array([0, 1])
col_indices = np.array([1, 0])
depth_indices = np.array([2, 1])

extracted_elements = extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices)
print(extracted_elements)

[6 8]


In [111]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def filter_elements_with_conditions(arr, condition1, condition2):
    filtered_elements = arr[condition1 & condition2]
    return filtered_elements

arr = np.array([10, 20, 5, 40, 30, 15])
condition1 = arr > 10
condition2 = arr < 40

filtered_arr = filter_elements_with_conditions(arr, condition1, condition2)
print(filtered_arr)

[20 30 15]


In [113]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elements_using_indices(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

extracted_elements = extract_elements_using_indices(arr_2d, row_indices, col_indices)
print(extracted_elements)

[2 6 7]


In [114]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
result = arr + 5
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [123]:
# 37. Consider two arrays arrl of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arrl using NumPy broadcasting.

arr1 = np.array([[1, 2, 3]]) 
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])
result = arr1 * arr2.T
result


array([[ 4, 16, 36],
       [ 5, 18, 39],
       [ 6, 20, 42],
       [ 7, 22, 45]])

In [133]:
# 38. Given a ID array arrl of shape (1, 4) and a 2D array arr2 of shape (4,3), add arrl to each row of arr2 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3, 4]]) 
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

result = arr2 + arr2
print(result)

[[10 12 14]
 [16 18 20]
 [22 24 26]
 [28 30 32]]


In [134]:
# 39. Consider two arrays arrl of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2
result

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [135]:
# 40. Given arrays arrl of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
arr2 = np.array([[7, 8], 
                 [9, 10]]) 
arr2_expanded = np.tile(arr2, (1, 3))
result = arr1 * arr2_expanded[:, :3]
result

array([[ 7, 16, 21],
       [36, 50, 54]])

In [136]:
# 41. Calculate column-wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

column_mean = np.mean(arr, axis=0)

print(column_mean)

[2.5 3.5 4.5]


In [138]:
# 42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

result = np.max(arr, axis=1)
result

array([3, 6])

In [4]:
# 43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

max_indic = np.argmax(arr, axis=0)

print(max_indic)

[1 1 1]


In [6]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr, window_size):
    rows, cols = arr.shape
    result = np.zeros_like(arr)
    
    for i in range(rows):
        for j in range(cols):
            
            start = max(0, j - window_size + 1)
            result[i, j] = np.sum(arr[i, start:j+1])
    
    return result
result = moving_sum(arr, window_size=2)
print(result)

[[ 1  3  5]
 [ 4  9 11]]


In [9]:
# 45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

are_all_even = np.all(arr % 2 == 0, axis=0)

print(are_all_even)

[False False False]


In [10]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and 'n' columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = original_array.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [12]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatten_matrix(matrix):
    return matrix.flatten()
    
flattened_array = flatten_matrix(input_matrix)

print(flattened_array)


[1 2 3 4 5 6]


In [13]:
# 48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]]) 
array2 = np.array([[5, 6], [7, 8]])

def concatenate_array(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)
result_axis_0 = concatenate_array(array1, array2, axis=0)
result_axis_1 = concatenate_array(array1, array2, axis=1)

In [14]:
print(result_axis_0)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
print(result_axis_1)

[[1 2 5 6]
 [3 4 7 8]]


In [28]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis. 
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(array, axis, sections):
    return np.split(array, sections, axis=axis)

result_axis_0 = split_array(original_array, axis=0, sections=3)
for sub_array in result_axis_0:
    print(sub_array)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [29]:
result_axis_1 = split_array(original_array, axis=1, sections=3)
for sub_array in result_axis_1:
    print(sub_array)

[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [31]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
#original_array = np.array([1, 2, 3, 4, 5])[2,4]
#indices_to_insert = [2, 4] values_to_insert = [10, 11]
#indices_to_delete = [1, 3]

In [33]:
# 51. Create a NumPy array arrl with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arrl' and `arr2.
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.array([1, 2, 3, 4, 5])

result = arr1 + arr2

In [34]:
arr1

array([2, 7, 6, 1, 2], dtype=int32)

In [35]:
arr2

array([1, 2, 3, 4, 5])

In [36]:
print(result)

[3 9 9 5 7]


In [37]:
# 52. Generate a NumPy array arrl with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arrl element-wise.

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

result = arr1 - arr2

In [38]:
arr1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [39]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
print(result)

[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [42]:
# 53. Create a NumPy array arrl with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arrl and arr2.
arr1 = np.random.randint(1, 5, size=4)
arr2 = np.array([1, 2, 3, 4])

result = arr1 * arr2

In [43]:
arr1

array([2, 2, 2, 4], dtype=int32)

In [44]:
arr2

array([1, 2, 3, 4])

In [45]:
print(result)

[ 2  4  6 16]


In [46]:
# 54. Generate a NumPy array arrl with even integers from 2 to 10 and another array 'arr2 with integers from 1 to 5. Perform element-wise division of arrl by arr2.
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

result = arr1 / arr2

In [47]:
arr1

array([ 2,  4,  6,  8, 10])

In [48]:
arr2

array([1, 2, 3, 4, 5])

In [49]:
print(result)

[2. 2. 2. 2. 2.]


In [50]:
# 55. Create a NumPy array arrl with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]

result = arr1 ** arr2

In [51]:
arr1

array([1, 2, 3, 4, 5])

In [52]:
arr2

array([5, 4, 3, 2, 1])

In [53]:
print(result)

[ 1 16 27 16  5]


In [56]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings. 
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring_occurances(arr, substring):
    count = np.sum(np.char.find(arr, substring) != -1)
    return count

substring = 'hello'
result = count_substring_occurances(arr, substring)
print(result)

3


In [57]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings. 
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(arr):
    uppercase_chars = []

    for string in arr:
        uppercase_chars.extend([char for char in string if char.isupper()])
    return ''.join(uppercase_chars)

result = extract_uppercase(arr)
print(result)

HWOAIGPT


In [58]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

result = replace_substring(arr, 'apple', 'orange')
print(result)

['orange' 'banana' 'grape' 'pineorange']


In [59]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array([ 'Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

result = concatenate_strings(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


In [60]:
#60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def find_longest_string_length(arr):
    lengths = np.char.str_len(arr)
    return np.max(lengths)

result = find_longest_string_length(arr)
print(result)

9


In [2]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, med,ian, variance, and standard deviation of the dataset using NumPy's functions.
data = np.random.randint(1, 1001, size=100)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

In [7]:
print(mean)

551.54


In [8]:
print(median)

619.5


In [9]:
print(variance)

91373.34839999997


In [10]:
print(std_deviation)

302.2802481142292


In [11]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

arr = np.random.randint(1, 100, size=50)

per_25 = np.percentile(arr, 25)
per_75 = np.percentile(arr, 75)

In [12]:
print(per_25)

30.0


In [13]:
print(per_75)

78.0


In [15]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's 'corrcoef function.
arr1 = np.random.randint(1, 101, size=100)
arr2 = np.random.randint(1, 101, size=100)

cor_matrix = np.corrcoef(arr1, arr2)
cor_coefficient = cor_matrix[0, 1]

In [16]:
arr1

array([44, 39, 86, 30, 30, 15, 16, 67, 93, 22, 59, 62, 29, 62, 91, 43, 60,
       81, 59, 71, 23, 12, 81, 38, 82, 30, 80, 79, 83, 20, 10, 27, 94, 10,
       84, 27, 58, 55, 21, 90, 98, 63, 30, 40,  6, 65, 51,  1, 84, 88, 74,
        1, 64, 26, 34, 59, 33, 77, 20, 42,  5, 73, 93, 92, 94, 43, 24, 20,
        5, 10, 18, 33,  4, 22,  1, 56, 80, 33, 90, 43, 20, 72, 19,  9, 91,
       59,  2, 65, 19, 64, 80, 97, 40, 44, 68, 40, 56, 80, 89, 62],
      dtype=int32)

In [17]:
arr2

array([ 12,  23,  98,  56,  77,  52,  66,  40,  21,  99,  70,  90,   8,
         5,  34, 100,  77,  24,  73,  12,  54,  28,  95,  30,  49,  94,
        83,  55,  56,  69,  19,  94,  94,  51,  62,   9,  28,  48,  80,
        46,  99,   4,  40,  91,  70,  55,  49,   8,  95, 100,  96,   5,
        80,  46,  97,  54,  75,  28,  38,  23,  48,  90,  36,  80,  25,
       100,  42,  79,  29,  31,  57,  66,  92,  27,  35,  97,   8,   3,
        28,  96,  87,  26,  62,  45,  19,  38,  52,  26,   3,  34,  81,
        28,  66,  60,  97,  40,  43,  15,  72,  28], dtype=int32)

In [18]:
print(cor_coefficient)

0.08313909236781289


In [20]:
# 64. Create two matrices and perform matrix multiplication using NumPy's 'dot function.
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[7, 8], [9, 10]])

result = np.dot(A, B)
print(result)

[[ 25  28]
 [ 57  64]
 [ 89 100]]


In [21]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

arr = np.random.randint(10, 1001, size=50)

per_10 = np.percentile(data, 10)
median = np.percentile(data, 50)
per_90 = np.percentile(data, 90)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

In [22]:
print(per_10)

126.80000000000001


In [23]:
print(median)

619.5


In [24]:
print(per_90)

914.2000000000002


In [25]:
print(q1)

257.25


In [26]:
print(q3)

823.25


In [29]:
# 66. Create a NumPy array of integers and find the index of a specific element.

arr = np.array([10, 20, 30, 40, 50])

index = np.where(arr == 30)
print(f"The index of 30 is : {index}")

The index of 30 is : (array([2]),)


In [30]:
# 67. Generate a random NumPy array and sort it in ascending order.
arr = np.random.randint(1, 101, size=10)

sorted_arr = np.sort(arr)

In [31]:
arr

array([81, 48, 29, 98, 10, 49, 43, 56, 16, 17], dtype=int32)

In [32]:
sorted_arr

array([10, 16, 17, 29, 43, 48, 49, 56, 81, 98], dtype=int32)

In [33]:
# 68. Filter elements >20 in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print(filtered_arr)

[25 42 30]


In [35]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]
print(filtered_arr)

[12 15]


In [37]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print(filtered_arr)

[20 30 40]


In [38]:
# 71. For the given NumPy array, check its byte order using the dtype attribute byteorder.
arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder
print(byte_order)

=


In [39]:
# 72. For the given NumPy array, perform byte swapping in place using 'byteswap().
arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

In [42]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.dtype.newbyteorder()

In [43]:
arr

array([1, 2, 3], dtype=int32)

In [44]:
print(swapped_arr)

>i4


In [46]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().
arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.dtype.newbyteorder('>' if arr.dtype.byteorder == '=' else '<')

In [47]:
arr

array([1, 2, 3], dtype=int32)

In [48]:
swapped_arr

dtype('>i4')

In [50]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute byteorder.
arr = np.array([1, 2, 3], dtype=np.int32)

system_byteorder = arr.dtype.byteorder
if system_byteorder == '=':
    print("The array is native byte order. No  byte swapping is neccesary")
else:
    print("The array is not native byte order. byte swapping is neccesary")

The array is native byte order. No  byte swapping is neccesary


In [54]:
# 76. Create a NumPy array arrl with values from 1 to 10. Create a copy of `arrl named copy_arr` and modify an element in copy_arr. Check if modifying copy_arr affects arrl`.

arr = np.arange(1, 11)

copy_arr = arr.copy()
copy_arr[0] = 100

In [55]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
copy_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [57]:
# 77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original `matrix.

matrix = np.random.randint(1, 10, size=(3, 3))

view_slice = matrix[:2, :2]

In [58]:
matrix

array([[4, 6, 2],
       [7, 6, 2],
       [1, 7, 5]], dtype=int32)

In [59]:
view_slice

array([[4, 6],
       [7, 6]], dtype=int32)

In [60]:
view_slice[0, 0] = 99

In [61]:
matrix

array([[99,  6,  2],
       [ 7,  6,  2],
       [ 1,  7,  5]], dtype=int32)

In [62]:
view_slice

array([[99,  6],
       [ 7,  6]], dtype=int32)

In [72]:
# 78. Create a NumPy array array_a of shape (4,3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.
arr = np.arange(1, 13).reshape(4, 3)
view_b = arr[1:3, 0:2]
view_b += 5

In [73]:
arr

array([[ 1,  2,  3],
       [ 9, 10,  6],
       [12, 13,  9],
       [10, 11, 12]])

In [74]:
view_b

array([[ 9, 10],
       [12, 13]])

In [78]:
# 79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it reflects changes in the original`orig_array`.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)

In [79]:
orig_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
reshaped_view[0, 0] = 100

In [81]:
reshaped_view

array([[100,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8]])

In [82]:
# 80. Create a NumPy array`data` of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy' and verify if it affects the original `data`.
data = np.random.randint(1, 11, size=(3, 4))

data_copy = data[data > 5].copy()
data_copy[0] = 100

In [83]:
data

array([[ 7,  8,  7,  2],
       [ 6,  6,  9,  3],
       [ 7,  5,  8, 10]], dtype=int32)

In [84]:
data_copy

array([100,   8,   7,   6,   6,   9,   7,   8,  10], dtype=int32)

In [85]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.random.randint(1, 11, size=(3, 4))
B = np.random.randint(1, 11, size=(3, 4))

add = A + B
sub = A - B

In [86]:
A

array([[ 4,  4,  5,  7],
       [10,  7,  3,  1],
       [ 3,  8,  5,  1]], dtype=int32)

In [87]:
B

array([[10,  6,  6,  1],
       [ 9,  5,  2,  5],
       [ 8,  4,  1,  3]], dtype=int32)

In [88]:
add

array([[14, 10, 11,  8],
       [19, 12,  5,  6],
       [11, 12,  6,  4]], dtype=int32)

In [89]:
sub

array([[-6, -2, -1,  6],
       [ 1,  2,  1, -4],
       [-5,  4,  4, -2]], dtype=int32)

In [91]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.random.randint(1, 11, size=(3, 2))
D = np.random.randint(1, 11, size=(2, 4))

result = C @ D

In [92]:
C

array([[ 6,  3],
       [ 9,  7],
       [10,  2]], dtype=int32)

In [93]:
D

array([[6, 2, 8, 9],
       [9, 8, 8, 5]], dtype=int32)

In [94]:
print(result)

[[ 63  36  72  69]
 [117  74 128 116]
 [ 78  36  96 100]]


In [95]:
# 83. Create a matrix `E` and find its transpose.

E = np.random.randint(1, 11, size=(3, 4))

E_transpose = E.T

In [96]:
E

array([[ 8, 10,  6,  9],
       [ 1,  3, 10,  3],
       [ 2,  1,  3,  5]], dtype=int32)

In [97]:
E_transpose

array([[ 8,  1,  2],
       [10,  3,  1],
       [ 6, 10,  3],
       [ 9,  3,  5]], dtype=int32)

In [98]:
# 84. Generate a square matrix F and compute its determinant.
F = np.random.randint(1, 11, size=(3, 3))

det_F = np.linalg.det(F)

In [99]:
F

array([[4, 7, 9],
       [4, 6, 1],
       [7, 6, 4]], dtype=int32)

In [100]:
det_F

np.float64(-152.99999999999997)

In [114]:
# 85. Create a square matrix `G`and find its inverse.
G = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

G_inv = np.linalg.inv(G)

In [115]:
G

array([[1, 2, 3],
       [0, 1, 4],
       [5, 6, 0]])

In [116]:
print(G_inv)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
